steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-f', 'Dockerfile.prod', '-t', 'us-central1-docker.pkg.dev/datapathdeployfastapi/repo-servicio-prediccion-datapath/image-v12-servicio-prediccion-datapath:latest', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/datapathdeployfastapi/repo-servicio-prediccion-datapath/image-v12-servicio-prediccion-datapath:latest']